name: lsp_client
description: A Dart client for communicating with the Dart analysis server using the Language Server Protocol (LSP).
version: 0.0.0-a1
publish_to: none
repository: https://github.com/enspyrco/lsp_client

environment:
  sdk: ^3.0.0

dependencies:
  stream_channel: ^2.1.1
  collection: ^1.18.0
  lsp_models:
    git: https://github.com/enspyrco/lsp_models

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
